// Создание переменной, отвечающей за относительную ссылку на каждую страницу

export const MAIN_ROUTE = "/"
export const CONTACTS = "/contacts"
export const INDUSTRIAL_P = "/industrial_partners"
export const EDUCATIONAL_P = "/educational_partners"
export const SCIENCE_P = "/science_partners"
export const EMPLOYERS_P = "/employers_partners"
export const HISTORY = "/history"
export const PERSONALITIES_PAGE = "/personalities"
export const STRUCTURE = "/structure"
export const INFO_EDU_ORG = "/information_about_the_educational_organization"
export const INTERNATIONAL_ACT = "/international_activities"
export const COUNTERING = "/countering_threats"
export const LEGAL_CLINIC = "/legal_clinic"
export const DOCUMENTS = "/documents"
export const ADMISSION_BAC = "/admission_bac"
export const ADMISSION_APE = "/admission_add"
export const SCIENCE = "/science"
export const STAFF = "/staff"
export const STUDENTS = "/students"
export const ADMIN = "/admin"
export const AUTH = "/auth"