// Создание переменной, отвечающей за относительную ссылку на каждую страницу

export const MAIN_ROUTE = "/"
export const ADMISSION_BAC = "/admission_bac"
export const ADMISSION_APE = "/admission_add"
export const INTERNATIONAL_ACT = "/international_activities"
export const NEWS = "/news"
export const ARTICLE = "/article"
export const PARTNERS = "/partners"
export const PERSONALITIES_PAGE = "/personalities"
export const STAFF = "/staff"
export const STUDENTS = "/students"

export const HISTORY = "/history"
export const LEGAL_CLINIC = "/legal_clinic"
export const SCIENCE = "/science"
export const PHOTO_GALLERY = "/photo_gallery"
export const LIBRARY = "/library"

export const INFO_EDU_ORG = "/sveden"
export const AVAILABLE_ENVIRONMENT = "/sveden/available_environment"
export const CONTACTS = "/sveden/contacts"
export const COUNTERING = "/sveden/countering_threats"
export const DOCUMENTS = "/sveden/documents"
export const EDUCATION = "/sveden/education"
export const FINANCIAL_ACTIVITY = "/sveden/financial_activity"
export const PAID_SERVICES = "/sveden/paid_services"
export const STRUCTURE = "/sveden/structure"
export const SUPPORT_AND_EQUIPMENT = "/sveden/support_and_equipment"
export const VACANT_PLACES = "/sveden/vacant_places"
export const WORKING_PROGRAMS = "/sveden/working_programs"
export const SCHOLARSHIPS_AND_OTHER_SUPPORT =  "/sveden/scholarships_and_other_support"
export const COMMON_INFO = "/sveden/common_info"
export const STANDARDS_AND_REQUIREMENTS = "/sveden/standards_and_requirements"

export const AUTH = "/athr"
export const ADMIN = "/admin"
export const SUPERADMIN = "/super_admin"