// Создание переменной, отвечающей за относительную ссылку на каждую страницу

export const TEST = "/test"
export const MAIN_ROUTE = "/"
export const CONTACTS = "/contacts"
export const HISTORY = "/history"
export const PERSONALITIES_PAGE = "/personalities"
export const STRUCTURE = "/structure"
export const INFO_EDU_ORG = "/information_about_the_educational_organization"
export const INTERNATIONAL_ACT = "/international_activities"
export const COUNTERING = "/countering_threats"
export const LEGAL_CLINIC = "/legal_clinic"
export const DOCUMENTS = "/documents"
export const ADMISSION_BAC = "/admission_bac"
export const ADMISSION_APE = "/admission_add"
export const SCIENCE = "/science"
export const STAFF = "/staff"
export const STUDENTS = "/students"
export const PARTNERS = "/partners"
export const NEWS = "/news"

export const AUTH = "/athr"

export const ADMIN = "/admin"
export const SUPERADMIN = "/super_admin"